// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Zf_83cxsmf1TO-NqiXdqZ_d7VC84HDI',
    appId: '1:234415652122:web:f52420f4cc0c268c2800a3',
    messagingSenderId: '234415652122',
    projectId: 'food-app-cdc56',
    authDomain: 'food-app-cdc56.firebaseapp.com',
    storageBucket: 'food-app-cdc56.appspot.com',
    measurementId: 'G-4D6YBJKM6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCerB9PXeEGFcq3Sua8HSOr3-BQtuMeA',
    appId: '1:234415652122:android:5db133e5a4a7e8142800a3',
    messagingSenderId: '234415652122',
    projectId: 'food-app-cdc56',
    storageBucket: 'food-app-cdc56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTV9CdqNdvlpd3hmNlyeBtk28YkRJ1hdg',
    appId: '1:234415652122:ios:02f7914891ffd2312800a3',
    messagingSenderId: '234415652122',
    projectId: 'food-app-cdc56',
    storageBucket: 'food-app-cdc56.appspot.com',
    iosClientId: '234415652122-cda5qh5dfvq6gttntujia02cdvha6j05.apps.googleusercontent.com',
    iosBundleId: 'com.sairakanwal.foodApp',
  );
}
